#!/usr/bin/env bash
set -euo pipefail

echo ""
echo "============================================================"
echo "INSTALL MAURIMESH FULL MESH TEST REPORT"
echo "Creates APK screen with full app activity/proof report"
echo "that can be copied as one block inside the APK."
echo "============================================================"
echo ""

ROOT="$(pwd)"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="$ROOT/backup-before-full-mesh-test-report-$STAMP"

mkdir -p "$BACKUP" \
  "$ROOT/app" \
  "$ROOT/src/components" \
  "$ROOT/src/maurimesh/full-mesh-test" \
  "$ROOT/docs"

if [ ! -f "$ROOT/package.json" ]; then
  echo "ERROR: package.json not found. Run this from /home/runner/workspace"
  exit 1
fi

backup_file() {
  local file="$1"
  if [ -f "$ROOT/$file" ]; then
    mkdir -p "$BACKUP/$(dirname "$file")"
    cp "$ROOT/$file" "$BACKUP/$file"
  fi
}

backup_file "app/dashboard.tsx"
backup_file "app/test-layer.tsx"
backup_file "src/lib/uiBackupRoutes.ts"
backup_file "src/maurimesh/test-layer/MauriMeshFullTestEngine.ts"

# ============================================================
# 1. GENERATE ROUTE REGISTRY FROM CURRENT APP FILES
# ============================================================

python3 <<'PY'
from pathlib import Path
import json
import re

root = Path(".")
app = root / "app"
out = root / "src/maurimesh/full-mesh-test/GeneratedRouteRegistry.ts"
out.parent.mkdir(parents=True, exist_ok=True)

routes = []

if app.exists():
    for p in sorted(app.rglob("*.tsx")):
        rel = p.relative_to(app).as_posix()
        if rel.startswith("_"):
            continue
        if rel.endswith("/_layout.tsx"):
            continue
        route = "/" + rel
        route = re.sub(r"\.tsx$", "", route)
        route = route.replace("/index", "")
        route = route.replace("[", ":").replace("]", "")
        if route == "":
            route = "/"
        routes.append({
            "route": route,
            "file": "app/" + rel,
            "label": route.strip("/").replace("-", " ").replace("/", " / ").title() or "Home",
        })

required = [
    "/dashboard",
    "/test-layer",
    "/full-mesh-test-report",
    "/native-telemetry",
    "/mauricore-ble-runtime",
    "/device-proof",
    "/proof-ledger",
    "/route-lab",
    "/message-fallback",
    "/jumpcode-proof",
    "/maori-protocols",
    "/evolution-layer",
    "/pixel-calling",
    "/ai-pixel-reconstruction",
    "/hybrid-wifi-ble-mesh",
    "/living-mesh",
    "/self-healing",
    "/settings",
]

existing = {r["route"] for r in routes}
registry = []
for r in routes:
    registry.append({
        **r,
        "required": r["route"] in required,
        "status": "PRESENT",
    })

for req in required:
    if req not in existing:
        registry.append({
            "route": req,
            "file": "MISSING",
            "label": req.strip("/").replace("-", " ").title(),
            "required": True,
            "status": "MISSING",
        })

ts = """// Auto-generated by install-maurimesh-full-mesh-test-report.sh
// Do not edit manually unless you regenerate the report registry.

export type GeneratedAppRoute = {
  route: string;
  file: string;
  label: string;
  required: boolean;
  status: "PRESENT" | "MISSING";
};

export const GENERATED_APP_ROUTES: GeneratedAppRoute[] = %s;
""" % json.dumps(registry, indent=2)

out.write_text(ts)
PY

# ============================================================
# 2. FULL MESH TEST TYPES
# ============================================================

cat > "$ROOT/src/maurimesh/full-mesh-test/FullMeshTestTypes.ts" <<'TS'
export type FullMeshCheckStatus =
  | "PASS"
  | "WARN"
  | "FAIL"
  | "APK_REQUIRED"
  | "TWO_PHONE_REQUIRED"
  | "THREE_PHONE_REQUIRED"
  | "NATIVE_REQUIRED"
  | "NOT_PROVEN";

export type FullMeshCheck = {
  id: string;
  title: string;
  status: FullMeshCheckStatus;
  detail: string;
  proofRequired: string[];
};

export type FullMeshReport = {
  id: string;
  generatedAt: string;
  appMode: "APK_IN_APP_REPORT";
  score: number;
  passCount: number;
  warnCount: number;
  failCount: number;
  apkRequiredCount: number;
  deviceProofRequiredCount: number;
  checks: FullMeshCheck[];
  routeInventory: {
    total: number;
    present: number;
    missing: number;
    requiredPresent: number;
    requiredMissing: number;
    lines: string[];
  };
  finalTruth: string;
  copyBlock: string;
};
TS

# ============================================================
# 3. FULL MESH TEST ENGINE
# ============================================================

cat > "$ROOT/src/maurimesh/full-mesh-test/FullMeshTestEngine.ts" <<'TS'
import { GENERATED_APP_ROUTES } from "./GeneratedRouteRegistry";
import { FullMeshCheck, FullMeshReport } from "./FullMeshTestTypes";

function nowIso() {
  return new Date().toISOString();
}

function check(
  id: string,
  title: string,
  status: FullMeshCheck["status"],
  detail: string,
  proofRequired: string[] = [],
): FullMeshCheck {
  return {
    id,
    title,
    status,
    detail,
    proofRequired,
  };
}

function statusScore(status: FullMeshCheck["status"]) {
  switch (status) {
    case "PASS":
      return 1;
    case "WARN":
      return 0.7;
    case "APK_REQUIRED":
      return 0.55;
    case "NATIVE_REQUIRED":
      return 0.45;
    case "TWO_PHONE_REQUIRED":
      return 0.35;
    case "THREE_PHONE_REQUIRED":
      return 0.25;
    case "NOT_PROVEN":
      return 0.2;
    case "FAIL":
      return 0;
    default:
      return 0;
  }
}

export function runFullMeshTestReport(): FullMeshReport {
  const generatedAt = nowIso();

  const routeLines = GENERATED_APP_ROUTES.map((route) => {
    const required = route.required ? "REQUIRED" : "OPTIONAL";
    return `${route.status.padEnd(7)} | ${required.padEnd(8)} | ${route.route} | ${route.file}`;
  });

  const requiredRoutes = GENERATED_APP_ROUTES.filter((route) => route.required);
  const requiredMissing = requiredRoutes.filter((route) => route.status === "MISSING");

  const checks: FullMeshCheck[] = [
    check(
      "app_bundle_loaded",
      "APK JavaScript bundle loaded",
      "PASS",
      "This screen is running inside the app bundle, so the React Native JS bundle loaded far enough to render the report UI.",
      ["Screenshot of this screen inside installed APK"],
    ),
    check(
      "route_inventory_generated",
      "Route inventory generated",
      requiredMissing.length === 0 ? "PASS" : "WARN",
      `Generated route inventory contains ${GENERATED_APP_ROUTES.length} routes. Required missing routes: ${requiredMissing.length}.`,
      ["GeneratedRouteRegistry.ts", "Visible route list in this report"],
    ),
    check(
      "dashboard_present",
      "Dashboard route present",
      hasRoute("/dashboard") ? "PASS" : "FAIL",
      "Dashboard is required as the main operator hub.",
      ["Open /dashboard inside APK"],
    ),
    check(
      "test_layer_present",
      "Test Layer route present",
      hasRoute("/test-layer") ? "PASS" : "FAIL",
      "Test Layer is required for in-app proof checks.",
      ["Open /test-layer inside APK"],
    ),
    check(
      "full_mesh_report_present",
      "Full Mesh Test Report route present",
      hasRoute("/full-mesh-test-report") ? "PASS" : "FAIL",
      "This screen provides the copyable full app activity/proof report.",
      ["Open /full-mesh-test-report inside APK"],
    ),
    check(
      "maori_protocol_layer",
      "Māori protocol fallback visible",
      hasRoute("/maori-protocols") ? "PASS" : "WARN",
      "Tikanga, Tapu, Noa, Mana, Mauri, Whakapapa Ara, Kaitiakitanga, Rangatiratanga, Whanaungatanga, Arotake, and APK-proof labels are expected.",
      ["Open /maori-protocols", "Confirm te reo/Tikanga labels visible"],
    ),
    check(
      "jumpcode_layer",
      "JumpCode proof route visible",
      hasRoute("/jumpcode-proof") ? "PASS" : "WARN",
      "JumpCode UI can be loaded from the APK. Real routing proof still requires packet/ACK evidence.",
      ["Open /jumpcode-proof", "Copy generated JumpCode", "Match routeId in logs later"],
    ),
    check(
      "evolution_layer",
      "Evolution Layer route visible",
      hasRoute("/evolution-layer") ? "PASS" : "WARN",
      "Evolution layer must observe, score, and recommend only. It must not silently rewrite code or fake proof.",
      ["Open /evolution-layer", "Confirm canAutoApply=false", "Confirm operator approval required"],
    ),
    check(
      "native_telemetry",
      "Native telemetry proof",
      "NATIVE_REQUIRED",
      "The APK must prove native telemetry through the installed Android app. JS fallback is allowed but remains a warning.",
      ["Open /native-telemetry", "Look for NATIVE_ANDROID or JS_FALLBACK", "Capture logcat"],
    ),
    check(
      "ble_runtime_screen",
      "BLE runtime screen",
      hasRoute("/mauricore-ble-runtime") ? "APK_REQUIRED" : "FAIL",
      "BLE runtime UI is present, but real BLE scan/advertise/connect/send/receive/ACK must be proven on physical devices.",
      ["Open /mauricore-ble-runtime", "Bluetooth ON", "Nearby Devices permission accepted"],
    ),
    check(
      "device_proof_screen",
      "Device Proof screen",
      hasRoute("/device-proof") ? "APK_REQUIRED" : "FAIL",
      "Device proof screen must show APK/device readiness without false live-BLE claims.",
      ["Open /device-proof", "Screenshot permissions and device checklist"],
    ),
    check(
      "proof_ledger_screen",
      "Proof Ledger screen",
      hasRoute("/proof-ledger") ? "PASS" : "WARN",
      "Proof Ledger route exists. Server persistence requires EXPO_PUBLIC_MESH_API_URL, otherwise local/UI proof only.",
      ["Open /proof-ledger", "Confirm proof entries or API fallback label"],
    ),
    check(
      "message_ack_fallback",
      "Message fallback / ACK rules",
      hasRoute("/message-fallback") ? "PASS" : "WARN",
      "Message fallback protects delivery honesty: pending proof remains pending until strict ACK or relay ACK evidence exists.",
      ["Open /message-fallback", "Confirm pending-proof labels"],
    ),
    check(
      "route_lab",
      "Route Lab decision screen",
      hasRoute("/route-lab") ? "PASS" : "WARN",
      "Route Lab should show BLE, relay, store-forward, Wi-Fi, gateway, trust, TTL, and path-score logic.",
      ["Open /route-lab", "Confirm selected route and fallback labels"],
    ),
    check(
      "hybrid_wifi_ble",
      "Hybrid Wi-Fi/BLE mesh layer",
      hasRoute("/hybrid-wifi-ble-mesh") ? "PASS" : "WARN",
      "Hybrid routing can select BLE, relay, store-forward, Wi-Fi local, Wi-Fi Direct-ready, and internet gateway fallback. Real radio proof still requires devices.",
      ["Open /hybrid-wifi-ble-mesh", "Confirm fallback ordering"],
    ),
    check(
      "living_mesh",
      "Living Mesh screen",
      hasRoute("/living-mesh") ? "PASS" : "WARN",
      "Living Mesh can show simulation/API/native status. It must clearly label simulation versus device proof.",
      ["Open /living-mesh", "Confirm no false live claim"],
    ),
    check(
      "self_healing",
      "Self-healing / homeostasis",
      hasRoute("/self-healing") ? "PASS" : "WARN",
      "Self-healing should recommend safe runtime changes and repairs. It must not claim physical repair or bypass Android protections.",
      ["Open /self-healing", "Confirm safe-mode and repair queue labels"],
    ),
    check(
      "pixel_calling",
      "Pixel Calling proof gate",
      hasRoute("/pixel-calling") ? "APK_REQUIRED" : "WARN",
      "Pixel Calling UI can be present, but real audio calling proof requires two phones, receiver acceptance, audio permission, and log evidence.",
      ["Open /pixel-calling", "Accept microphone permission", "Two-phone audio proof"],
    ),
    check(
      "ai_pixel_reconstruction",
      "AI Pixel Reconstruction proof gate",
      hasRoute("/ai-pixel-reconstruction") ? "APK_REQUIRED" : "WARN",
      "AI pixel reconstruction must not claim raw 32K live. It can claim reconstruction only with source frame hash, quality score, reconstructed frame hash, and ACK.",
      ["Open /ai-pixel-reconstruction", "Confirm RAW_32K_LIVE_FALSE", "Capture ACK proof later"],
    ),
    check(
      "one_device_apk",
      "One real device APK test",
      "APK_REQUIRED",
      "One phone can prove APK install, launch, route loading, Bluetooth state, permission visibility, and no fatal crash. It cannot prove phone-to-phone delivery.",
      ["Install APK", "Open required routes", "ADB logcat no AndroidRuntime/FATAL/ReactNativeJS fatal"],
    ),
    check(
      "two_phone_ble_ack",
      "Two-phone BLE ACK proof",
      "TWO_PHONE_REQUIRED",
      "Real BLE delivery requires Phone A sender and Phone B receiver with matching packetId, routeId, TX/RX, and ACK evidence.",
      [
        "PHONE_A_TX_BLE_START",
        "PHONE_B_RX_BLE_FROM_A",
        "PHONE_B_ACK_SENT",
        "PHONE_A_ACK_RECEIVED",
        "matching packetId",
        "matching routeId",
      ],
    ),
    check(
      "three_hop_ble_relay",
      "Three-hop BLE relay proof",
      "THREE_PHONE_REQUIRED",
      "Three-hop proof requires Phone A sender, Phone B relay, Phone C receiver, forwarded packet proof, and strict ACK path.",
      [
        "PHONE_A_TX_BLE_START",
        "PHONE_B_RX_BLE_FROM_A",
        "PHONE_B_RELAY_TX_TO_C",
        "PHONE_C_RX_BLE_FROM_B",
        "PHONE_C_STRICT_ACK_SENT",
        "PHONE_A_STRICT_OR_RELAY_ACK_RECEIVED",
      ],
    ),
    check(
      "rust_apk_bridge",
      "Rust APK bridge proof",
      "NOT_PROVEN",
      "Rust source is not enough. APK proof requires Android .so, Gradle wiring, JNI/UniFFI bridge, loadLibrary, and runtime call evidence.",
      ["Android .so exists", "System.loadLibrary exists", "Runtime bridge screen calls Rust safely"],
    ),
    check(
      "no_false_claims",
      "No false proof claims",
      "PASS",
      "The report keeps unproven BLE, ACK, relay, native telemetry, Pixel Calling, and Rust as APK/device proof gates.",
      ["Truth labels visible", "Unproven items remain NOT_PROVEN/APK_REQUIRED"],
    ),
  ];

  const weighted = checks.reduce((sum, item) => sum + statusScore(item.status), 0);
  const score = Math.round((weighted / checks.length) * 100);

  const passCount = checks.filter((item) => item.status === "PASS").length;
  const warnCount = checks.filter((item) => item.status === "WARN").length;
  const failCount = checks.filter((item) => item.status === "FAIL").length;
  const apkRequiredCount = checks.filter((item) => item.status === "APK_REQUIRED" || item.status === "NATIVE_REQUIRED").length;
  const deviceProofRequiredCount = checks.filter((item) =>
    item.status === "TWO_PHONE_REQUIRED" ||
    item.status === "THREE_PHONE_REQUIRED" ||
    item.status === "NOT_PROVEN",
  ).length;

  const finalTruth =
    "This is an in-APK full mesh test report. It proves the APK can render the report and validates route/proof readiness from bundled app data. It does not by itself prove real BLE TX/RX, receiver ACK, relay delivery, native telemetry, Rust JNI, or Pixel Calling audio. Those require physical devices and logcat evidence.";

  const copyBlock = buildCopyBlock({
    generatedAt,
    score,
    passCount,
    warnCount,
    failCount,
    apkRequiredCount,
    deviceProofRequiredCount,
    checks,
    routeLines,
    finalTruth,
  });

  return {
    id: "MAURIMESH_FULL_MESH_TEST_REPORT",
    generatedAt,
    appMode: "APK_IN_APP_REPORT",
    score,
    passCount,
    warnCount,
    failCount,
    apkRequiredCount,
    deviceProofRequiredCount,
    checks,
    routeInventory: {
      total: GENERATED_APP_ROUTES.length,
      present: GENERATED_APP_ROUTES.filter((route) => route.status === "PRESENT").length,
      missing: GENERATED_APP_ROUTES.filter((route) => route.status === "MISSING").length,
      requiredPresent: requiredRoutes.filter((route) => route.status === "PRESENT").length,
      requiredMissing: requiredMissing.length,
      lines: routeLines,
    },
    finalTruth,
    copyBlock,
  };
}

function hasRoute(route: string) {
  return GENERATED_APP_ROUTES.some((item) => item.route === route && item.status === "PRESENT");
}

function buildCopyBlock(input: {
  generatedAt: string;
  score: number;
  passCount: number;
  warnCount: number;
  failCount: number;
  apkRequiredCount: number;
  deviceProofRequiredCount: number;
  checks: FullMeshCheck[];
  routeLines: string[];
  finalTruth: string;
}) {
  const lines: string[] = [];

  lines.push("============================================================");
  lines.push("MAURIMESH FULL MESH TEST REPORT");
  lines.push("============================================================");
  lines.push(`Generated: ${input.generatedAt}`);
  lines.push("Mode: APK_IN_APP_REPORT");
  lines.push(`Score: ${input.score}%`);
  lines.push(`PASS: ${input.passCount}`);
  lines.push(`WARN: ${input.warnCount}`);
  lines.push(`FAIL: ${input.failCount}`);
  lines.push(`APK/NATIVE REQUIRED: ${input.apkRequiredCount}`);
  lines.push(`DEVICE PROOF REQUIRED: ${input.deviceProofRequiredCount}`);
  lines.push("");

  lines.push("------------------------------------------------------------");
  lines.push("CHECKS");
  lines.push("------------------------------------------------------------");

  input.checks.forEach((item, index) => {
    lines.push(`${index + 1}. [${item.status}] ${item.title}`);
    lines.push(`   ID: ${item.id}`);
    lines.push(`   Detail: ${item.detail}`);
    if (item.proofRequired.length > 0) {
      lines.push("   Proof required:");
      item.proofRequired.forEach((proof) => {
        lines.push(`   - ${proof}`);
      });
    }
    lines.push("");
  });

  lines.push("------------------------------------------------------------");
  lines.push("ROUTE INVENTORY");
  lines.push("------------------------------------------------------------");
  input.routeLines.forEach((line) => lines.push(line));

  lines.push("");
  lines.push("------------------------------------------------------------");
  lines.push("REAL DEVICE PROOF STILL REQUIRED");
  lines.push("------------------------------------------------------------");
  lines.push("- Installed APK no-crash logcat");
  lines.push("- Native telemetry state");
  lines.push("- Bluetooth permission/state proof");
  lines.push("- Phone A TX_BLE_START");
  lines.push("- Phone B RX_BLE_FROM_A");
  lines.push("- Phone B ACK_SENT");
  lines.push("- Phone A ACK_RECEIVED");
  lines.push("- Matching packetId");
  lines.push("- Matching routeId");
  lines.push("- Proof ledger hash");
  lines.push("- Three-hop relay if claiming 3-hop mesh");
  lines.push("- Pixel Calling real audio proof if claiming live call");
  lines.push("- Rust .so/JNI/loadLibrary proof if claiming Rust inside APK");

  lines.push("");
  lines.push("------------------------------------------------------------");
  lines.push("FINAL TRUTH");
  lines.push("------------------------------------------------------------");
  lines.push(input.finalTruth);
  lines.push("============================================================");

  return lines.join("\n");
}
TS

cat > "$ROOT/src/maurimesh/full-mesh-test/index.ts" <<'TS'
export * from "./FullMeshTestTypes";
export * from "./FullMeshTestEngine";
export * from "./GeneratedRouteRegistry";
TS

# ============================================================
# 4. UI COMPONENT
# ============================================================

cat > "$ROOT/src/components/FullMeshTestReportPanel.tsx" <<'TSX'
import React, { useMemo, useState } from "react";
import {
  Alert,
  Platform,
  Pressable,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";
import { runFullMeshTestReport } from "../maurimesh/full-mesh-test";
import { MaoriProtocolPanel } from "./MaoriProtocolPanel";

const C = {
  bg: "#020403",
  panel: "rgba(2,12,8,0.92)",
  panel2: "rgba(1,8,5,0.94)",
  border: "rgba(0,208,132,0.32)",
  green: "#00D084",
  emerald: "#10B981",
  blue: "#38BDF8",
  white: "#FFFFFF",
  muted: "rgba(255,255,255,0.72)",
  warn: "#F59E0B",
  danger: "#FB7185",
};

function Pill({ label, color = C.green }: { label: string; color?: string }) {
  return (
    <View style={[styles.pill, { borderColor: color }]}>
      <Text style={[styles.pillText, { color }]}>{label}</Text>
    </View>
  );
}

function Button({
  title,
  onPress,
}: {
  title: string;
  onPress: () => void;
}) {
  return (
    <Pressable onPress={onPress} style={styles.button}>
      <Text style={styles.buttonText}>{title}</Text>
    </Pressable>
  );
}

export function FullMeshTestReportPanel() {
  const initialReport = useMemo(() => runFullMeshTestReport(), []);
  const [report, setReport] = useState(initialReport);

  const rerun = () => {
    setReport(runFullMeshTestReport());
  };

  const shareReport = async () => {
    try {
      await Share.share({
        title: "MauriMesh Full Mesh Test Report",
        message: report.copyBlock,
      });
    } catch (error) {
      Alert.alert(
        "Share unavailable",
        "Use the report box below. Long press inside it, select all, then copy.",
      );
    }
  };

  const copyFallback = () => {
    Alert.alert(
      "Copy report",
      Platform.OS === "android"
        ? "Long press inside the report box below, choose Select all, then Copy. Or press Share Report."
        : "Long press inside the report box below, choose Select all, then Copy. Or press Share Report.",
    );
  };

  const scoreColor =
    report.score >= 90 ? C.green : report.score >= 70 ? C.warn : C.danger;

  return (
    <ScrollView style={styles.root} contentContainerStyle={styles.content}>
      <View style={styles.header}>
        <Pill label="FULL MESH TEST" color={C.blue} />
        <Text style={styles.title}>Full Mesh Test Report</Text>
        <Text style={styles.subtitle}>
          One in-APK report for full app activity, mesh proof gates, route inventory,
          Māori protocol, JumpCode, Evolution, ACK, relay, native telemetry, and final truth.
        </Text>
      </View>

      <View style={styles.panel}>
        <View style={styles.row}>
          <Pill label={`${report.score}%`} color={scoreColor} />
          <Pill label={`PASS ${report.passCount}`} />
          <Pill label={`WARN ${report.warnCount}`} color={C.warn} />
          <Pill label={`FAIL ${report.failCount}`} color={report.failCount > 0 ? C.danger : C.green} />
        </View>

        <Text style={styles.sectionTitle}>Report Summary</Text>
        <Text style={styles.line}>Generated: {report.generatedAt}</Text>
        <Text style={styles.line}>Mode: {report.appMode}</Text>
        <Text style={styles.line}>Routes: {report.routeInventory.present}/{report.routeInventory.total} present</Text>
        <Text style={styles.line}>Required routes missing: {report.routeInventory.requiredMissing}</Text>
        <Text style={styles.truth}>{report.finalTruth}</Text>

        <View style={styles.buttonRow}>
          <Button title="Run Full Mesh Test" onPress={rerun} />
          <Button title="Share Report" onPress={shareReport} />
          <Button title="Copy Help" onPress={copyFallback} />
        </View>
      </View>

      <MaoriProtocolPanel screen="Full Mesh Test Report" compact />

      <View style={styles.panel}>
        <Text style={styles.sectionTitle}>Checks</Text>
        {report.checks.map((item, index) => {
          const color =
            item.status === "PASS"
              ? C.green
              : item.status === "WARN" || item.status === "APK_REQUIRED" || item.status === "NATIVE_REQUIRED"
                ? C.warn
                : C.danger;

          return (
            <View key={item.id} style={styles.check}>
              <Text style={[styles.checkTitle, { color }]}>
                {index + 1}. [{item.status}] {item.title}
              </Text>
              <Text style={styles.line}>{item.detail}</Text>
              {item.proofRequired.map((proof) => (
                <Text key={proof} style={styles.bullet}>• {proof}</Text>
              ))}
            </View>
          );
        })}
      </View>

      <View style={styles.panel}>
        <Text style={styles.sectionTitle}>Copyable Full Report Block</Text>
        <Text style={styles.line}>
          Long press in the box, select all, copy. You can paste this whole block back into ChatGPT.
        </Text>
        <TextInput
          value={report.copyBlock}
          multiline
          editable={false}
          selectTextOnFocus
          style={styles.reportBox}
          textAlignVertical="top"
        />
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg },
  content: { padding: 18, gap: 14, paddingBottom: 42 },
  header: { gap: 10 },
  title: { color: C.white, fontSize: 34, fontWeight: "900", letterSpacing: -1 },
  subtitle: { color: C.muted, fontSize: 15, lineHeight: 22 },
  panel: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 24,
    backgroundColor: C.panel,
    padding: 16,
    gap: 10,
  },
  row: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  buttonRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 6 },
  button: {
    backgroundColor: C.green,
    borderRadius: 16,
    paddingVertical: 11,
    paddingHorizontal: 14,
  },
  buttonText: { color: "#00150D", fontWeight: "900", fontSize: 13 },
  pill: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  pillText: { fontSize: 11, fontWeight: "900", letterSpacing: 0.7 },
  sectionTitle: { color: C.white, fontSize: 21, fontWeight: "900" },
  line: { color: C.muted, fontSize: 13, lineHeight: 20 },
  bullet: { color: C.muted, fontSize: 12, lineHeight: 18 },
  truth: { color: C.warn, fontSize: 12, lineHeight: 18 },
  check: {
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
    paddingTop: 10,
    gap: 4,
  },
  checkTitle: { fontSize: 14, fontWeight: "900", lineHeight: 20 },
  reportBox: {
    minHeight: 420,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    borderRadius: 16,
    backgroundColor: C.panel2,
    color: C.white,
    padding: 12,
    fontSize: 11,
    lineHeight: 16,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
});
TSX

# ============================================================
# 5. ROUTE
# ============================================================

cat > "$ROOT/app/full-mesh-test-report.tsx" <<'TSX'
import React from "react";
import { FullMeshTestReportPanel } from "../src/components/FullMeshTestReportPanel";

export default function FullMeshTestReportScreen() {
  return <FullMeshTestReportPanel />;
}
TSX

# ============================================================
# 6. DASHBOARD WIRING
# ============================================================

if [ -f "$ROOT/app/dashboard.tsx" ] && ! grep -q "/full-mesh-test-report" "$ROOT/app/dashboard.tsx"; then
  python3 <<'PY'
from pathlib import Path

p = Path("app/dashboard.tsx")
src = p.read_text()

button = '<MauriButton title="Full Mesh Test Report" onPress={() => router.push("/full-mesh-test-report")} />'

markers = [
    '<MauriButton title="Full App Test" onPress={() => router.push("/test-layer")} />',
    '<MauriButton title="Evolution Layer" onPress={() => router.push("/evolution-layer")} />',
    '<MauriButton title="Māori Protocols" onPress={() => router.push("/maori-protocols")} />',
    '<MauriButton title="JumpCode Proof" onPress={() => router.push("/jumpcode-proof")} />',
]

inserted = False
for marker in markers:
    if marker in src:
        src = src.replace(marker, marker + "\n        " + button, 1)
        inserted = True
        break

if not inserted:
    src += '\n\n// MauriMesh Full Mesh Test Report route: /full-mesh-test-report\n'

p.write_text(src)
PY
fi

# ============================================================
# 7. TEST LAYER MARKER
# ============================================================

if [ -f "$ROOT/app/test-layer.tsx" ] && ! grep -q "/full-mesh-test-report" "$ROOT/app/test-layer.tsx"; then
  cat >> "$ROOT/app/test-layer.tsx" <<'TS'

// MauriMesh Full Mesh Test Report route marker.
// Open /full-mesh-test-report for one-block APK activity/proof report.
TS
fi

# ============================================================
# 8. BACKUP ROUTE REGISTRY
# ============================================================

if [ -f "$ROOT/src/lib/uiBackupRoutes.ts" ] && ! grep -q "/full-mesh-test-report" "$ROOT/src/lib/uiBackupRoutes.ts"; then
  cat >> "$ROOT/src/lib/uiBackupRoutes.ts" <<'TS'

// MauriMesh Full Mesh Test Report backup route marker
export const MAURIMESH_FULL_MESH_TEST_REPORT_ROUTE = "/full-mesh-test-report";
TS
fi

ENGINE="$ROOT/src/maurimesh/test-layer/MauriMeshFullTestEngine.ts"
if [ -f "$ENGINE" ] && ! grep -q '"/full-mesh-test-report"' "$ENGINE"; then
  python3 <<'PY'
from pathlib import Path

p = Path("src/maurimesh/test-layer/MauriMeshFullTestEngine.ts")
src = p.read_text()

for marker in ['  "/test-layer",', '  "/evolution-layer",', '  "/maori-protocols",', '  "/jumpcode-proof",']:
    if marker in src:
        src = src.replace(marker, marker + '\n  "/full-mesh-test-report",', 1)
        break
else:
    src += '\n\n// MauriMesh Full Mesh Test Report required route: /full-mesh-test-report\n'

p.write_text(src)
PY
fi

# ============================================================
# 9. CHECKER
# ============================================================

cat > "$ROOT/check-maurimesh-full-mesh-test-report.sh" <<'EOF_CHECK'
#!/usr/bin/env bash
set -euo pipefail

ROOT="$(pwd)"
STAMP="$(date +%Y%m%d-%H%M%S)"
REPORT="$ROOT/docs/maurimesh-full-mesh-test-report-$STAMP.md"
LATEST="$ROOT/docs/maurimesh-full-mesh-test-report-latest.md"
EXPORT_DIR="$ROOT/.maurimesh-full-mesh-test-export-$STAMP"

mkdir -p "$ROOT/docs"
: > "$REPORT"

TOTAL=0
PASS=0
FAIL=0

check_file() {
  local label="$1"
  local file="$2"
  TOTAL=$((TOTAL+1))
  if [ -f "$ROOT/$file" ]; then
    echo "- [x] $label exists: $file" >> "$REPORT"
    PASS=$((PASS+1))
  else
    echo "- [ ] MISSING: $label: $file" >> "$REPORT"
    FAIL=$((FAIL+1))
  fi
}

check_contains() {
  local label="$1"
  local file="$2"
  local needle="$3"
  TOTAL=$((TOTAL+1))
  if [ -f "$ROOT/$file" ] && grep -q "$needle" "$ROOT/$file"; then
    echo "- [x] $label" >> "$REPORT"
    PASS=$((PASS+1))
  else
    echo "- [ ] MISSING: $label" >> "$REPORT"
    FAIL=$((FAIL+1))
  fi
}

{
  echo "# MauriMesh Full Mesh Test Report Install Check"
  echo ""
  echo "Generated: $STAMP"
  echo ""
  echo "## Files"
} >> "$REPORT"

check_file "Generated route registry" "src/maurimesh/full-mesh-test/GeneratedRouteRegistry.ts"
check_file "Full Mesh Test types" "src/maurimesh/full-mesh-test/FullMeshTestTypes.ts"
check_file "Full Mesh Test engine" "src/maurimesh/full-mesh-test/FullMeshTestEngine.ts"
check_file "Full Mesh Test index" "src/maurimesh/full-mesh-test/index.ts"
check_file "Full Mesh Test panel" "src/components/FullMeshTestReportPanel.tsx"
check_file "Full Mesh Test route" "app/full-mesh-test-report.tsx"

{
  echo ""
  echo "## Markers"
} >> "$REPORT"

check_contains "Copy block marker" "src/maurimesh/full-mesh-test/FullMeshTestEngine.ts" "MAURIMESH FULL MESH TEST REPORT"
check_contains "Final truth boundary" "src/maurimesh/full-mesh-test/FullMeshTestEngine.ts" "does not by itself prove real BLE"
check_contains "Two-phone proof gate" "src/maurimesh/full-mesh-test/FullMeshTestEngine.ts" "TWO_PHONE_REQUIRED"
check_contains "Three-hop proof gate" "src/maurimesh/full-mesh-test/FullMeshTestEngine.ts" "THREE_PHONE_REQUIRED"
check_contains "Native proof gate" "src/maurimesh/full-mesh-test/FullMeshTestEngine.ts" "NATIVE_REQUIRED"
check_contains "Rust proof gate" "src/maurimesh/full-mesh-test/FullMeshTestEngine.ts" "Rust APK bridge proof"
check_contains "Māori protocol panel included" "src/components/FullMeshTestReportPanel.tsx" "MaoriProtocolPanel"
check_contains "TextInput copy box included" "src/components/FullMeshTestReportPanel.tsx" "TextInput"
check_contains "Share report included" "src/components/FullMeshTestReportPanel.tsx" "Share.share"
check_contains "Dashboard route marker" "app/dashboard.tsx" "/full-mesh-test-report"
check_contains "Backup route marker" "src/lib/uiBackupRoutes.ts" "/full-mesh-test-report"

{
  echo ""
  echo "## TypeScript"
} >> "$REPORT"

TOTAL=$((TOTAL+1))
if npx tsc --noEmit >> "$REPORT" 2>&1; then
  echo "- [x] TypeScript passed" >> "$REPORT"
  PASS=$((PASS+1))
else
  echo "- [ ] TypeScript failed" >> "$REPORT"
  FAIL=$((FAIL+1))
fi

{
  echo ""
  echo "## Expo Android Export"
} >> "$REPORT"

TOTAL=$((TOTAL+1))
rm -rf "$EXPORT_DIR"
if NODE_ENV=production npx expo export --platform android --output-dir "$EXPORT_DIR" >> "$REPORT" 2>&1; then
  echo "- [x] Expo Android export passed" >> "$REPORT"
  PASS=$((PASS+1))
else
  echo "- [ ] Expo Android export failed" >> "$REPORT"
  FAIL=$((FAIL+1))
fi

BUNDLE_FILE="$(find "$EXPORT_DIR" -type f \( -name '*.hbc' -o -name '*.js' \) | head -1 || true)"

{
  echo ""
  echo "## Bundle Marker Search"
} >> "$REPORT"

TOTAL=$((TOTAL+1))
if [ -n "$BUNDLE_FILE" ] && strings "$BUNDLE_FILE" | grep -Ei "MAURIMESH FULL MESH TEST REPORT|Full Mesh Test Report|TWO_PHONE_REQUIRED|THREE_PHONE_REQUIRED|NATIVE_REQUIRED|does not by itself prove real BLE" >> "$REPORT" 2>&1; then
  echo "- [x] Full Mesh Test Report markers found in Android bundle" >> "$REPORT"
  PASS=$((PASS+1))
else
  echo "- [ ] Full Mesh Test Report markers not confirmed in Android bundle" >> "$REPORT"
  FAIL=$((FAIL+1))
fi

SCORE=$(( PASS * 100 / TOTAL ))
STATUS="COMPLETE"
if [ "$FAIL" -gt 0 ]; then
  STATUS="FAILED"
fi

{
  echo ""
  echo "## Summary"
  echo ""
  echo "- Total: $TOTAL"
  echo "- Complete: $PASS"
  echo "- Missing/failed: $FAIL"
  echo "- Score: $SCORE%"
  echo "- Status: **$STATUS**"
  echo ""
  echo "## Final Truth"
  echo ""
  echo "The Full Mesh Test Report screen is installed."
  echo "It provides one copyable in-APK activity/proof report block."
  echo "It does not fake BLE, ACK, relay, native telemetry, Rust, or Pixel Calling proof."
} >> "$REPORT"

cp "$REPORT" "$LATEST"
cat "$REPORT"

echo ""
echo "============================================================"
echo "FULL MESH TEST REPORT CHECK COMPLETE"
echo "Status: $STATUS"
echo "Score: $SCORE%"
echo "Report: $LATEST"
echo "============================================================"

if [ "$STATUS" != "COMPLETE" ]; then
  exit 1
fi
EOF_CHECK

chmod +x "$ROOT/check-maurimesh-full-mesh-test-report.sh"

# ============================================================
# 10. RUN CHECK
# ============================================================

./check-maurimesh-full-mesh-test-report.sh

echo ""
echo "============================================================"
echo "DONE: FULL MESH TEST REPORT INSTALLED"
echo "============================================================"
echo "Backup:"
echo "  $BACKUP"
echo ""
echo "Open in APK:"
echo "  /full-mesh-test-report"
echo ""
echo "Report:"
echo "  docs/maurimesh-full-mesh-test-report-latest.md"
echo "============================================================"
