// Pure (DB-free, Express-free) shaping/validation for two-phone hardware proof
// evidence. Kept separate from proofRoutes.ts so it can be unit-tested without
// pulling in drizzle/the Postgres pool.

// Canonical event type for evidence generated by a real two-phone hardware proof
// run and submitted to the server for permanent recording. proofLedger has no
// dedicated `type`/jsonb column, so the type lives in eventType and the full
// evidence JSON is stored verbatim in rawLogExcerpt.
export const TWO_PHONE_EVIDENCE_TYPE = "two_phone_hardware_evidence";

// Structural shape of a proofLedger insert row produced from evidence. Matches
// the columns used by proofRoutes' db.insert(proofLedger).values(...).
export interface ProofEvidenceRow {
  eventType: string;
  runtimeMode: string;
  source: string;
  verified: boolean;
  deviceId?: string;
  peerId?: string;
  packetId?: string;
  routeId?: string;
  ackId?: string;
  rawLogExcerpt: string;
}

// Cap the stored payload so a single submission cannot bloat the permanent
// ledger with an oversized blob. This is a lightweight integrity guard; it is
// NOT authentication — proper write-protection/rate-limiting is tracked
// separately (the mobile client currently submits without an auth token).
export const MAX_EVIDENCE_BYTES = 64 * 1024;

const asOptString = (v: unknown): string | undefined =>
  typeof v === "string" && v.length > 0 ? v : undefined;

// Validate + shape an incoming evidence payload into a proofLedger row. Accepts
// either the raw evidence object or an envelope of the form { evidence: {...} }.
export function normalizeProofEvidence(body: unknown): ProofEvidenceRow {
  const envelope = (body ?? {}) as Record<string, unknown>;
  const evidence =
    envelope.evidence && typeof envelope.evidence === "object"
      ? (envelope.evidence as Record<string, unknown>)
      : (envelope as Record<string, unknown>);

  if (!evidence || typeof evidence !== "object" || Array.isArray(evidence)) {
    throw new Error("evidence must be a JSON object");
  }
  if (Object.keys(evidence).length === 0) {
    throw new Error("evidence object must not be empty");
  }

  const rawLogExcerpt = JSON.stringify(evidence);
  if (Buffer.byteLength(rawLogExcerpt, "utf8") > MAX_EVIDENCE_BYTES) {
    throw new Error(`evidence exceeds ${MAX_EVIDENCE_BYTES} byte limit`);
  }

  return {
    eventType: TWO_PHONE_EVIDENCE_TYPE,
    // Not "real_native": the server cannot attest BLE. This is client-submitted.
    runtimeMode: "client_submitted_evidence",
    source: "mobile_two_phone_proof",
    verified: false,
    deviceId: asOptString(evidence.deviceId),
    peerId: asOptString(evidence.peerId),
    packetId: asOptString(evidence.packetId),
    routeId: asOptString(evidence.routeId),
    ackId: asOptString(evidence.ackId),
    rawLogExcerpt,
  };
}
