import { SystemLayer } from "./systemTypes";

export const MAURIMESH_SYSTEM_LAYERS: SystemLayer[] = [
  {
    id: "offline_identity_mesh",
    name: "Offline-First Identity Mesh Messenger",
    status: "ACTIVE",
    purpose: "Keeps identity and communication local-first before internet fallback.",
    belongsBecause: "MauriMesh must survive without SIM, mobile data, or central server dependency.",
    optimises: ["identity", "offline messaging", "trust", "local-first startup"],
    dependencies: ["secure_mesh_identity", "delivery_ledger"],
    proofBoundary: "Needs APK/device proof for native BLE identity exchange.",
  },
  {
    id: "living_route_memory",
    name: "Living Route Memory",
    status: "LEARNING",
    purpose: "Learns from ACKs, failures, latency, and relay behaviour.",
    belongsBecause: "The route system must improve while the build and field tests run.",
    optimises: ["route quality", "delivery success", "latency", "relay selection"],
    dependencies: ["delivery_ledger", "decentralised_trust_memory"],
    proofBoundary: "Logic active now. Real field learning needs phone packet events.",
  },
  {
    id: "tikanga_governance",
    name: "Tikanga Protocol Engine",
    status: "ACTIVE",
    purpose: "Classifies messages into noa, tapu, whānau, manaakitanga, kaitiakitanga, and Kia Kaha states.",
    belongsBecause: "MauriMesh needs ethical and cultural decision logic before routing.",
    optimises: ["consent", "privacy", "cultural protocol", "safe routing"],
    dependencies: ["self_governance", "cultural_intelligence"],
    proofBoundary: "Requires cultural review before public claims.",
  },
  {
    id: "self_governance",
    name: "Self-Governance Layer",
    status: "ACTIVE",
    purpose: "Approves, restricts, or rejects routing decisions before transmission.",
    belongsBecause: "A self-learning mesh needs control boundaries.",
    optimises: ["safety", "abuse prevention", "policy control", "trusted routing"],
    dependencies: ["tikanga_governance", "trust_memory"],
    proofBoundary: "Runtime logic active. Production policy requires review.",
  },
  {
    id: "mauri_ai_core",
    name: "Mauri AI Core",
    status: "OPTIMISING",
    purpose: "Balances route score, trust, battery, privacy, urgency, and delivery likelihood.",
    belongsBecause: "The network needs a decision brain, not fixed static routing.",
    optimises: ["routing", "energy", "fallback", "resilience", "priority"],
    dependencies: ["living_route_memory", "self_governance"],
    proofBoundary: "Weights need tuning from real field telemetry.",
  },
  {
    id: "adaptive_routing",
    name: "Adaptive Mesh Routing Intelligence",
    status: "LEARNING",
    purpose: "Chooses direct, relay, gateway, or store-and-forward routes.",
    belongsBecause: "Hybrid networks constantly change.",
    optimises: ["transport selection", "hop quality", "path score", "fallback"],
    dependencies: ["mauri_ai_core", "hybrid_transport"],
    proofBoundary: "Needs native BLE/Wi-Fi Direct proof for real routes.",
  },
  {
    id: "hybrid_transport",
    name: "Hybrid Transport Routing Layer",
    status: "WIRED",
    purpose: "Unifies BLE, Wi-Fi Direct, local Wi-Fi, internet, and future backhaul options.",
    belongsBecause: "No single transport is strong enough everywhere.",
    optimises: ["connectivity", "fallback", "coverage", "route survival"],
    dependencies: ["adaptive_routing"],
    proofBoundary: "BLE/Wi-Fi Direct need APK testing.",
  },
  {
    id: "store_forward",
    name: "Store-and-Forward Delivery Layer",
    status: "ACTIVE",
    purpose: "Stores packets until a trusted route appears.",
    belongsBecause: "Offline recipients cannot always receive immediately.",
    optimises: ["delayed delivery", "offline survival", "queue recovery"],
    dependencies: ["delivery_ledger", "self_healing"],
    proofBoundary: "Needs encrypted persistent APK storage.",
  },
  {
    id: "self_healing",
    name: "Self-Healing Runtime",
    status: "ACTIVE",
    purpose: "Detects failed packets, stale nodes, and requeue conditions.",
    belongsBecause: "The mesh must repair itself when routes fail.",
    optimises: ["recovery", "uptime", "queue health", "runtime stability"],
    dependencies: ["delivery_ledger", "store_forward"],
    proofBoundary: "Needs Android background service proof.",
  },
  {
    id: "delivery_ledger",
    name: "Delivery Proof and ACK Ledger",
    status: "ACTIVE",
    purpose: "Records created, queued, sent, stored, failed, delivered, and ACK events.",
    belongsBecause: "Sent is not the same as delivered.",
    optimises: ["proof", "debugging", "learning", "trust scoring"],
    dependencies: ["adaptive_routing"],
    proofBoundary: "Logic active. Device proof requires native transport events.",
  },
  {
    id: "decentralised_trust_memory",
    name: "Decentralised Trust Memory",
    status: "LEARNING",
    purpose: "Raises or lowers node trust through behaviour.",
    belongsBecause: "Relay trust must be earned, not assumed.",
    optimises: ["relay safety", "bad-route avoidance", "network quality"],
    dependencies: ["delivery_ledger", "living_route_memory"],
    proofBoundary: "Needs signed relay evidence in production.",
  },
  {
    id: "cultural_intelligence",
    name: "Cultural Intelligence Layer",
    status: "ACTIVE",
    purpose: "Applies context-aware behaviour for privacy, language, care, and community use.",
    belongsBecause: "MauriMesh is not only technical; it carries community protocol.",
    optimises: ["community fit", "language", "care logic", "privacy context"],
    dependencies: ["tikanga_governance"],
    proofBoundary: "Needs cultural review and configurable community policy.",
  },
  {
    id: "cleo_chanelle_synth",
    name: "Cleo + Chanelle Synth AI Federation",
    status: "WIRED",
    purpose: "Explains routing, governance, and delivery state to humans.",
    belongsBecause: "Users need the living mesh explained clearly.",
    optimises: ["user understanding", "education", "family-safe explanation"],
    dependencies: ["mauri_ai_core", "delivery_ledger"],
    proofBoundary: "Voice/personality synthesis remains future layer.",
  },
  {
    id: "living_visual_proof",
    name: "Living Mesh Visual Proof Layer",
    status: "WIRED",
    purpose: "Shows nodes, routes, trust, ledger, and route quality.",
    belongsBecause: "Visible proof builds trust and speeds debugging.",
    optimises: ["visibility", "testing", "investor proof", "debugging"],
    dependencies: ["delivery_ledger", "adaptive_routing"],
    proofBoundary: "Needs live native telemetry for real-world proof.",
  },
  {
    id: "kia_kaha_emergency",
    name: "Kia Kaha Emergency Routing Mode",
    status: "ACTIVE",
    purpose: "Raises priority, TTL, and recovery behaviour for emergency messages.",
    belongsBecause: "MauriMesh must work hardest when people need help.",
    optimises: ["urgent delivery", "priority routing", "resilience"],
    dependencies: ["self_governance", "adaptive_routing"],
    proofBoundary: "Needs abuse prevention and emergency field tests.",
  },
  {
    id: "completion_puller",
    name: "Completion Puller",
    status: "OPTIMISING",
    purpose: "Finds missing wiring, missing screens, and incomplete proof boundaries.",
    belongsBecause: "The build must pull incomplete parts into place as it evolves.",
    optimises: ["completion", "screen coverage", "integration accuracy"],
    dependencies: ["button_decision_router", "system_brain"],
    proofBoundary: "Replit can audit files. Native proof still external.",
  },
  {
    id: "button_decision_router",
    name: "Button Decision Router",
    status: "ACTIVE",
    purpose: "Maps every UI button to the correct system layer, screen, or native-proof boundary.",
    belongsBecause: "Buttons must not point randomly; every action must serve the right layer.",
    optimises: ["navigation", "decision accuracy", "UI wiring"],
    dependencies: ["system_brain"],
    proofBoundary: "Static screen mapping active. Full AST rewrite is intentionally avoided for safety.",
  },
];
