// Auto-generated by install-maurimesh-full-mesh-test-report.sh
// Do not edit manually unless you regenerate the report registry.

export type GeneratedAppRoute = {
  route: string;
  file: string;
  label: string;
  required: boolean;
  status: "PRESENT" | "MISSING";
};

export const GENERATED_APP_ROUTES: GeneratedAppRoute[] = [
  {
    "route": "/ack-tracking",
    "file": "app/ack-tracking.tsx",
    "label": "Ack Tracking",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/add-friend",
    "file": "app/add-friend.tsx",
    "label": "Add Friend",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/ai-pixel-reconstruction",
    "file": "app/ai-pixel-reconstruction.tsx",
    "label": "Ai Pixel Reconstruction",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/api-config",
    "file": "app/api-config.tsx",
    "label": "Api Config",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/backup-intelligence",
    "file": "app/backup-intelligence.tsx",
    "label": "Backup Intelligence",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/ble-hardware-runtime",
    "file": "app/ble-hardware-runtime.tsx",
    "label": "Ble Hardware Runtime",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/ble-proof",
    "file": "app/ble-proof.tsx",
    "label": "Ble Proof",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/chat",
    "file": "app/chat.tsx",
    "label": "Chat",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/dashboard",
    "file": "app/dashboard.tsx",
    "label": "Dashboard",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/delivery-analytics",
    "file": "app/delivery-analytics.tsx",
    "label": "Delivery Analytics",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/device-hardware",
    "file": "app/device-hardware.tsx",
    "label": "Device Hardware",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/device-proof",
    "file": "app/device-proof.tsx",
    "label": "Device Proof",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/evolution-layer",
    "file": "app/evolution-layer.tsx",
    "label": "Evolution Layer",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/foreground-runtime-proof",
    "file": "app/foreground-runtime-proof.tsx",
    "label": "Foreground Runtime Proof",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/hardware-runtime",
    "file": "app/hardware-runtime.tsx",
    "label": "Hardware Runtime",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/hybrid-wifi-ble-mesh",
    "file": "app/hybrid-wifi-ble-mesh.tsx",
    "label": "Hybrid Wifi Ble Mesh",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/",
    "file": "app/index.tsx",
    "label": "Home",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/integration-hub",
    "file": "app/integration-hub.tsx",
    "label": "Integration Hub",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/intelligence",
    "file": "app/intelligence.tsx",
    "label": "Intelligence",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/jumpcode-proof",
    "file": "app/jumpcode-proof.tsx",
    "label": "Jumpcode Proof",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/latency-monitoring",
    "file": "app/latency-monitoring.tsx",
    "label": "Latency Monitoring",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/live-mesh-ops",
    "file": "app/live-mesh-ops.tsx",
    "label": "Live Mesh Ops",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/living-mesh",
    "file": "app/living-mesh.tsx",
    "label": "Living Mesh",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/login",
    "file": "app/login.tsx",
    "label": "Login",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/maori-protocols",
    "file": "app/maori-protocols.tsx",
    "label": "Maori Protocols",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/mauricore-ble-runtime",
    "file": "app/mauricore-ble-runtime.tsx",
    "label": "Mauricore Ble Runtime",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/mauricore-governance",
    "file": "app/mauricore-governance.tsx",
    "label": "Mauricore Governance",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/mesh/ack-tracking",
    "file": "app/mesh/ack-tracking.tsx",
    "label": "Mesh / Ack Tracking",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/mesh/ble-discovery",
    "file": "app/mesh/ble-discovery.tsx",
    "label": "Mesh / Ble Discovery",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/mesh",
    "file": "app/mesh/index.tsx",
    "label": "Mesh",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/mesh/packet-analysis",
    "file": "app/mesh/packet-analysis.tsx",
    "label": "Mesh / Packet Analysis",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/mesh/peer-mapping",
    "file": "app/mesh/peer-mapping.tsx",
    "label": "Mesh / Peer Mapping",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/mesh/relay-analytics",
    "file": "app/mesh/relay-analytics.tsx",
    "label": "Mesh / Relay Analytics",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/mesh/signal-strength",
    "file": "app/mesh/signal-strength.tsx",
    "label": "Mesh / Signal Strength",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/mesh/store-forward-queue",
    "file": "app/mesh/store-forward-queue.tsx",
    "label": "Mesh / Store Forward Queue",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/mesh-status",
    "file": "app/mesh-status.tsx",
    "label": "Mesh Status",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/message-fallback",
    "file": "app/message-fallback.tsx",
    "label": "Message Fallback",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/native-ble-audit",
    "file": "app/native-ble-audit.tsx",
    "label": "Native Ble Audit",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/native-ble-scan-proof",
    "file": "app/native-ble-scan-proof.tsx",
    "label": "Native Ble Scan Proof",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/native-ble-status",
    "file": "app/native-ble-status.tsx",
    "label": "Native Ble Status",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/native-telemetry",
    "file": "app/native-telemetry.tsx",
    "label": "Native Telemetry",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/network/delivery-analytics",
    "file": "app/network/delivery-analytics.tsx",
    "label": "Network / Delivery Analytics",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/network/latency-monitoring",
    "file": "app/network/latency-monitoring.tsx",
    "label": "Network / Latency Monitoring",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/network/route-health",
    "file": "app/network/route-health.tsx",
    "label": "Network / Route Health",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/operator-console",
    "file": "app/operator-console.tsx",
    "label": "Operator Console",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/pixel-calling-backup",
    "file": "app/pixel-calling-backup.tsx",
    "label": "Pixel Calling Backup",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/pixel-calling",
    "file": "app/pixel-calling.tsx",
    "label": "Pixel Calling",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/proof-ledger",
    "file": "app/proof-ledger.tsx",
    "label": "Proof Ledger",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/proof-metrics",
    "file": "app/proof-metrics.tsx",
    "label": "Proof Metrics",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/raw-packet-proof",
    "file": "app/raw-packet-proof.tsx",
    "label": "Raw Packet Proof",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/route-health",
    "file": "app/route-health.tsx",
    "label": "Route Health",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/route-lab",
    "file": "app/route-lab.tsx",
    "label": "Route Lab",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/self-healing",
    "file": "app/self-healing.tsx",
    "label": "Self Healing",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/settings",
    "file": "app/settings.tsx",
    "label": "Settings",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/store-forward-queue",
    "file": "app/store-forward-queue.tsx",
    "label": "Store Forward Queue",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/test-layer",
    "file": "app/test-layer.tsx",
    "label": "Test Layer",
    "required": true,
    "status": "PRESENT"
  },
  {
    "route": "/tikanga-engine",
    "file": "app/tikanga-engine.tsx",
    "label": "Tikanga Engine",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/ui-roadmap",
    "file": "app/ui-roadmap.tsx",
    "label": "Ui Roadmap",
    "required": false,
    "status": "PRESENT"
  },
  {
    "route": "/full-mesh-test-report",
    "file": "MISSING",
    "label": "Full Mesh Test Report",
    "required": true,
    "status": "MISSING"
  }
];
